quarkus.http.port=8080
quarkus.native.compression.level=9

app.api.limit=${APP_API_LIMIT:130}
app.api.timeout=${APP_API_TIMEOUT:4000}

quarkus.smallrye-openapi.enable=true
quarkus.smallrye-openapi.info.title=Quarkus Rate Limiting API
quarkus.smallrye-openapi.info.version=1.0.0
quarkus.swagger-ui.always-include=true

